# Generated by Django 5.2.4 on 2026-01-26 12:55

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='content',
            field=tinymce.models.HTMLField(default='', help_text='Full service page content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_image',
            field=models.ImageField(blank=True, null=True, upload_to='seo/'),
        ),
        migrations.AddField(
            model_name='service',
            name='seo_title',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Short text for homepage cards'),
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.service')),
            ],
        ),
    ]
